name: "Flutter Analyze Commenter"

description: "Auto comment on PRs based on Flutter Analyze results"

author: "yorifuji"

branding:
  icon: code
  color: blue

inputs:
  analyze-log:
    description: "Path to the log file(s) by flutter analyze command, separated by commas"
    required: false
  custom-lint-log:
    description: "(Optional) Paths to the log file(s) by dart run custom_lint command, separated by commas"
    required: false
  verbose:
    description: "Enable verbose logging"
    required: false
    default: false
  analyze_log:
    description: "Path to the Flutter analyze log file"
    deprecationMessage: "Use `analyze-log` instead"
    required: false
  max-issues:
    description: "Maximum number of issues to comment"
    required: false
    default: 10

runs:
  using: composite
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      if: ${{ github.event_name == 'pull_request' }}
      env:
        ANALYZE_LOG: ${{ inputs.analyze-log }}
        ANALYZE_LOG_DEPRECATED: ${{ inputs.analyze_log }}
        CUSTOM_LINT_LOG: ${{ inputs.custom-lint-log }}
        VERBOSE: ${{ inputs.verbose }}
        MAX_ISSUES: ${{ inputs.max-issues }}
      with:
        retries: 3
        script: |
          const analyzeLog = process.env.ANALYZE_LOG || process.env.ANALYZE_LOG_DEPRECATED;
          const customLintLog = process.env.CUSTOM_LINT_LOG;
          const verboseLogging = process.env.VERBOSE === 'true';

          const workingDir = process.env.GITHUB_WORKSPACE;
          const actionPath = process.env.GITHUB_ACTION_PATH;
          const maxIssues = parseInt(process.env.MAX_ISSUES);

          const path = require('path');
          const script = require(path.join(actionPath, 'index.js'));
          await script({ core, github, context, workingDir, analyzeLog, customLintLog, verboseLogging, maxIssues })
